name: Build Vue and Deploy Node App

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:


#    - name: Copy dist to backend/public
#      run: |
#        rm -rf backend/public
#        mkdir -p backend/public
#        cp -r frontapp/dist/* backend/public/

    - name: Setup SSH key
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

    # 서버에 접속하여 배포 실행          
    - name: SSH into server and deploy
      run: |
        ssh -vvv -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "bash ~/start1.sh"
